### ISSUE TITLE
Questions about using 2 or 3 views to train

### ISSUE THREAD

**Issue by RichardChen20** [bastianwandt/CanonPose#4]
Hi, may I ask a question about train using 2 or 3 views. When only use 2 views to train, did you randomly select 2 views or use fixed views like view1 and view2? When testing, did you use all view to calculate MPJPE? I would appreciate a lot if you could reply!

**Comment by bastianwandt** [comment]
Hi,
we used multiple configurations for two views but once selected the cameras stayed the same. That means if cameras 1 and 2 are selected only they are used in the complete training set. The results didn't change significantly if we used cameras 1-2, 2-3, 3-4, or 1-4. However, for two views we made sure that we don't choose cameras that are opposite of each other.
During testing each image is evaluated individually. There is no averaging over views before calculating the MPJPE.

**Comment by RichardChen20** [comment]
Thanks a lot for your reply! I found a situation that when i used 2 cameras like 1-2 or 2-3 to tarin, the MPJPE increased by about 10mm. However, when 3 cameras are used to tarin, the performance didn't change significantly. As reported in your paper, the performance should not change a lot when only 2 cameras are used to train, I don't know what leads to the degradtaion. (All 4 views are used to calculated MPJPE)
